-- fordo.meal_type definition

-- Drop table

-- DROP TABLE fordo.meal_type;

CREATE TABLE fordo.meal_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	meal_type_label varchar NOT NULL,
	is_active bool NOT NULL,
	CONSTRAINT meal_type_pkey PRIMARY KEY (id)
);


-- fordo.recipe definition

-- Drop table

-- DROP TABLE fordo.recipe;

CREATE TABLE fordo.recipe (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	recipe_name varchar NULL,
	description varchar NULL,
	prep_time int4 NULL,
	cook_time int4 NULL,
	calorie_count numeric(10, 2) NULL,
	serving_size int2 NULL,
	is_active bool NOT NULL,
	CONSTRAINT recipe_pkey PRIMARY KEY (id)
);


-- fordo.tag definition

-- Drop table

-- DROP TABLE fordo.tag;

CREATE TABLE fordo.tag (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tag_label varchar NOT NULL,
	is_active bool NOT NULL,
	CONSTRAINT tag_pkey PRIMARY KEY (id),
	CONSTRAINT tag_tag_label_key UNIQUE (tag_label)
);


-- fordo.ingredient definition

-- Drop table

-- DROP TABLE fordo.ingredient;

CREATE TABLE fordo.ingredient (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ingredient_name varchar NULL,
	ingredient_details varchar NULL,
	linked_recipe int4 NULL,
	is_active bool NOT NULL,
	CONSTRAINT ingredient_pkey PRIMARY KEY (id),
	CONSTRAINT fk_ingredient_recipe FOREIGN KEY (linked_recipe) REFERENCES fordo.recipe(id) ON DELETE CASCADE
);


-- fordo.ingredient_local_name definition

-- Drop table

-- DROP TABLE fordo.ingredient_local_name;

CREATE TABLE fordo.ingredient_local_name (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ingredient_id int4 NOT NULL,
	local_name varchar NOT NULL,
	is_active bool NOT NULL,
	CONSTRAINT ingredient_local_name_pkey PRIMARY KEY (id),
	CONSTRAINT fk_ingredient_ingredient_local_name FOREIGN KEY (ingredient_id) REFERENCES fordo.ingredient(id) ON DELETE CASCADE
);


-- fordo.note definition

-- Drop table

-- DROP TABLE fordo.note;

CREATE TABLE fordo.note (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title varchar NULL,
	body varchar NULL,
	recipe_id int4 NOT NULL,
	is_active bool NOT NULL,
	CONSTRAINT note_pkey PRIMARY KEY (id),
	CONSTRAINT fk_recipe_note FOREIGN KEY (recipe_id) REFERENCES fordo.recipe(id) ON DELETE CASCADE
);


-- fordo.recipe_ingredient_map definition

-- Drop table

-- DROP TABLE fordo.recipe_ingredient_map;

CREATE TABLE fordo.recipe_ingredient_map (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	recipe_id int4 NOT NULL,
	ingredient_id int4 NOT NULL,
	is_active bool NOT NULL,
	quantity int4 NULL,
	unit varchar NULL,
	CONSTRAINT recipe_ingredient_map_pkey PRIMARY KEY (id),
	CONSTRAINT fk_recipe_ingredient_map_ingredient FOREIGN KEY (ingredient_id) REFERENCES fordo.ingredient(id) ON DELETE CASCADE,
	CONSTRAINT fk_recipe_ingredient_map_recipe FOREIGN KEY (recipe_id) REFERENCES fordo.recipe(id) ON DELETE CASCADE
);


-- fordo.recipe_meal_type_map definition

-- Drop table

-- DROP TABLE fordo.recipe_meal_type_map;

CREATE TABLE fordo.recipe_meal_type_map (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	recipe_id int4 NOT NULL,
	meal_type_id int4 NOT NULL,
	is_active bool NOT NULL,
	CONSTRAINT recipe_meal_type_map_pkey PRIMARY KEY (id),
	CONSTRAINT fk_recipe_meal_type_map_meal_type FOREIGN KEY (meal_type_id) REFERENCES fordo.meal_type(id) ON DELETE CASCADE,
	CONSTRAINT fk_recipe_meal_type_map_recipe FOREIGN KEY (recipe_id) REFERENCES fordo.recipe(id) ON DELETE CASCADE
);


-- fordo.recipe_step definition

-- Drop table

-- DROP TABLE fordo.recipe_step;

CREATE TABLE fordo.recipe_step (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	recipe_id int4 NULL,
	sort_order int2 NULL,
	title varchar NULL,
	body varchar NULL,
	is_active bool NOT NULL,
	CONSTRAINT recipe_step_pkey PRIMARY KEY (id),
	CONSTRAINT fk_recipe_steps_recipe FOREIGN KEY (recipe_id) REFERENCES fordo.recipe(id) ON DELETE CASCADE
);


-- fordo.recipe_tag_map definition

-- Drop table

-- DROP TABLE fordo.recipe_tag_map;

CREATE TABLE fordo.recipe_tag_map (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	recipe_id int4 NOT NULL,
	tag_id int4 NOT NULL,
	is_active bool NOT NULL,
	CONSTRAINT tag_map_pkey PRIMARY KEY (id),
	CONSTRAINT fk_recipe_tag_map FOREIGN KEY (recipe_id) REFERENCES fordo.recipe(id) ON DELETE CASCADE,
	CONSTRAINT fk_tag_tag_map FOREIGN KEY (tag_id) REFERENCES fordo.tag(id) ON DELETE CASCADE
);